### ISSUE TITLE
Risk of Options set as a required dependency

### ISSUE THREAD

**Issue by PollyEdaline** [VarnaScelestus/RoR2#5]
It seems that the new update requires Risk of Options to even load at all, despite not actually downloading it automatically from the Thunderstore.

**Comment by PollyEdaline** [comment]
Actually, it still doesn't load even after installing Risk of Options. Here's a log:

[LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8445642/LogOutput.log)

Here's another log from a clean testing profile, just in case (the mod doesn't load on either profile):

[LogOutput.log](https://github.com/VarnaScelestus/RoR2/files/8445654/LogOutput.log)

**Comment by VarnaScelestus** [comment]
Thanks for letting me know. It ended up being related to an issue involving how thunderstore ignores plugin directory structure. This is fixed in the newest version.

The Risk of Options dependency is actually another issue that is fixed, and I'll have that on thunderstore after I put together a few more fixes with it.
